# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-18.4
packages:
  - secure-memory
  - NaCl
  - crypto-sodium
  - crypto-sodium-streamly

extra-deps:
  # - libsodium-1.0.18.2
  # This is the same as above, but from git, since hackage.nix
  # seems to be stuck and does not include this version
  - git: https://github.com/k0001/hs-libsodium
    commit: 39dbda30a3fff3e456e2f695072f7ab48f0d7336
    subdirs: [libsodium]

nix:
  packages:
    - pkgconfig
    - libsodium

    # new streamly wants this
    # - darwin.apple_sdk.frameworks.Cocoa
